from typing import Protocol

from app.identity.domain.entities import Group


class GroupCommandRepositoryProtocol(Protocol):
    """Protocol for group command repository (write operations)."""

    async def create(self, group: Group) -> str: ...

    async def update(self, id: str, group: Group) -> str: ...

    async def delete(self, id: str) -> None: ...

    async def add_user(self, group_id: str, user_id: str) -> None: ...

    async def remove_user(self, group_id: str, user_id: str) -> None: ...

    async def add_permission(self, group_id: str, permission_id: str) -> None: ...

    async def remove_permission(self, group_id: str, permission_id: str) -> None: ...

    async def get_group_users(self, group_id: str) -> list[str]: ...

    async def get_group_permissions(self, group_id: str) -> list[str]: ...
