"""add groups and perms

Revision ID: b3adeb11da96
Revises: 8e511f7165cb
Create Date: 2026-03-17 00:39:00.291251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3adeb11da96'
down_revision: Union[str, Sequence[str], None] = '8e511f7165cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permissions',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('codename', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_permissions'))
    )
    op.create_index(op.f('ix_permissions_codename'), 'permissions', ['codename'], unique=True)
    op.create_index(op.f('ix_permissions_created_at'), 'permissions', ['created_at'], unique=False)
    op.create_index(op.f('ix_permissions_id'), 'permissions', ['id'], unique=False)
    op.create_index(op.f('ix_permissions_updated_at'), 'permissions', ['updated_at'], unique=False)
    op.create_table('groups',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(length=2048), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_groups_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_groups_updated_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_groups'))
    )
    op.create_index(op.f('ix_groups_created_at'), 'groups', ['created_at'], unique=False)
    op.create_index(op.f('ix_groups_deleted_at'), 'groups', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_groups_id'), 'groups', ['id'], unique=False)
    op.create_index(op.f('ix_groups_name'), 'groups', ['name'], unique=True)
    op.create_index(op.f('ix_groups_updated_at'), 'groups', ['updated_at'], unique=False)
    op.create_table('group_permissions_m2m',
    sa.Column('group_id', sa.UUID(), nullable=False),
    sa.Column('permission_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], name=op.f('fk_group_permissions_m2m_group_id_groups'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], name=op.f('fk_group_permissions_m2m_permission_id_permissions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('group_id', 'permission_id', 'id', name=op.f('pk_group_permissions_m2m'))
    )
    op.create_index(op.f('ix_group_permissions_m2m_group_id'), 'group_permissions_m2m', ['group_id'], unique=False)
    op.create_index(op.f('ix_group_permissions_m2m_id'), 'group_permissions_m2m', ['id'], unique=False)
    op.create_index(op.f('ix_group_permissions_m2m_permission_id'), 'group_permissions_m2m', ['permission_id'], unique=False)
    op.create_table('user_groups_m2m',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('group_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], name=op.f('fk_user_groups_m2m_group_id_groups'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_groups_m2m_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'group_id', 'id', name=op.f('pk_user_groups_m2m'))
    )
    op.create_index(op.f('ix_user_groups_m2m_group_id'), 'user_groups_m2m', ['group_id'], unique=False)
    op.create_index(op.f('ix_user_groups_m2m_id'), 'user_groups_m2m', ['id'], unique=False)
    op.create_index(op.f('ix_user_groups_m2m_user_id'), 'user_groups_m2m', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_groups_m2m_user_id'), table_name='user_groups_m2m')
    op.drop_index(op.f('ix_user_groups_m2m_id'), table_name='user_groups_m2m')
    op.drop_index(op.f('ix_user_groups_m2m_group_id'), table_name='user_groups_m2m')
    op.drop_table('user_groups_m2m')
    op.drop_index(op.f('ix_group_permissions_m2m_permission_id'), table_name='group_permissions_m2m')
    op.drop_index(op.f('ix_group_permissions_m2m_id'), table_name='group_permissions_m2m')
    op.drop_index(op.f('ix_group_permissions_m2m_group_id'), table_name='group_permissions_m2m')
    op.drop_table('group_permissions_m2m')
    op.drop_index(op.f('ix_groups_updated_at'), table_name='groups')
    op.drop_index(op.f('ix_groups_name'), table_name='groups')
    op.drop_index(op.f('ix_groups_id'), table_name='groups')
    op.drop_index(op.f('ix_groups_deleted_at'), table_name='groups')
    op.drop_index(op.f('ix_groups_created_at'), table_name='groups')
    op.drop_table('groups')
    op.drop_index(op.f('ix_permissions_updated_at'), table_name='permissions')
    op.drop_index(op.f('ix_permissions_id'), table_name='permissions')
    op.drop_index(op.f('ix_permissions_created_at'), table_name='permissions')
    op.drop_index(op.f('ix_permissions_codename'), table_name='permissions')
    op.drop_table('permissions')
    # ### end Alembic commands ###
